# Generated by Django 3.0.5 on 2020-07-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='edays',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='esub1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='econtact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.AddField(
            model_name='employee',
            name='esub2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub6',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub7',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub8',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
