# Generated by Django 3.0.5 on 2020-07-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200726_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='esub3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub5',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub6',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub7',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub8',
        ),
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='edays',
            field=models.CharField(max_length=100),
        ),
    ]
