# Generated by Django 3.0.5 on 2020-07-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20200726_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esub3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub6',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub7',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub8',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
