# Generated by Django 3.0.5 on 2020-07-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200726_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='esub3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub5',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub6',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub7',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esub8',
        ),
    ]
