# Generated by Django 3.0.5 on 2020-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_employee_esub3'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esub4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
