# Generated by Django 3.0.5 on 2020-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20200726_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esub6',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub7',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='esub8',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
